### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Bhavishya2912** [surya7765/citymart#4]
Hey,
Just viewed your project and found that you are missing license and standard contributing guideline. I wish to help you in this items.

Including this items your project will be more visible and more actively contributed by many the opensource contributors.

Please tell me what kind of license is your project established on & do you accept and give recognition to the contributor from hacktoberfest?

**Comment by surya7765** [comment]
Yes, sure you can go ahead.

**Comment by surya7765** [comment]
Thanks for the update.
